version: "3.8"

services:
  nginx-rtmp:
    container_name: evsev-nginx
    build:
      context: ./nginx

    restart: unless-stopped
    ports:
      - "7778:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/hls:rw
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`evsev.sametak.com`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.services.web.loadbalancer.server.port=7777"
      - "traefik.http.routers.web.tls.certresolver=cloudflare"
      - "traefik.http.routers.web.service=web"

  frontend:
    container_name: evsev-frontend
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    working_dir: /app
    networks:
      - proxy

  backend:
    container_name: evsev-backend
    build:
      context: ./backend
    ports:
      - "5000:5000" # API dışarı açıldı
    networks:
      - proxy
networks:
  proxy:
    external: true # Traefik'in kullandığı ağ
